name: Build-OS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3

      - name: Setup-and-Patch
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.tar.xz
          tar -xf linux-6.9.tar.xz
          mv linux-6.9 kernel_source
          cp physics_patch.c kernel_source/kernel/sched/physics_patch.c
          cp boot_name.c kernel_source/init/boot_name.c
          echo "تمت إضافة اسم أحمد أسامة بنجاح!"
