name: Build-OS
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Code
        uses: actions/checkout@v3

      - name: Test-Build
        run: |
          echo "جاري تجهيز نظام أحمد أسامة..."
          uname -a
          echo "النظام جاهز لاستقبال الأكواد الخاصة بك."
